### ISSUE TITLE
Prep for release

### ISSUE THREAD

**Issue by irfanhakim-as** [irfanhakim-as/wg-quicker#1]
# TODO

- [x] Add versioning
- [x] Add help message
- [x] Add optional parameters
- [x] Add releases workflow
- [x] Update documentation
- [x] Add license
